name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-24.04

    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Pkl
        uses: pkl-community/setup-pkl@v0
        with:
          pkl-version: "0.27.1"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependecies
        run: |
          sudo apt update
          sudo apt install --no-install-recommends --no-upgrade -y just
          
      - name: Install semenatic-release dependecies
        run: |
          npm install @semantic-release/exec -D
          npm install @semantic-release/git -D
          npm install @semantic-release/github -D
          npm install @semantic-release/commit-analyzer -D
          npm install @semantic-release/release-notes-generator -D
          npm install conventional-changelog-conventionalcommits -D
      - name: Run tests
        run: |
          pkl test

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release